### ISSUE TITLE
Add Dependencies to outer build.sbt

### ISSUE THREAD

**Issue by valencik** [typelevel/typelevel.g8#13]
Looks like Scala Steward will only update the inner template dependencies if they are also added to the outside build.sbt

https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md#can-scala-steward-update-dependencies-in-giter8-templates-

I don’t think Scala Steward will update anything in `default.properties`

**Comment by armanbilge** [comment]
https://github.com/typelevel/typelevel.g8/blob/50f545c596a828ba048fdbc4d12338702477d84b/src/main/g8/default.properties#L7-L11

The sbt-typelevel version can probably be hard-coded into the `plugins.sbt`. Regarding the sbt version, does g8 not make the `build.properties` file by itself?

Dunno what to do about Scala versions.

**Comment by valencik** [comment]
As far as I can tell, Scala Steward doesn't have any specific support for giter8 templates, and thus can't help us maintain anything in default.properties.

> I think this works good enough and warrants no special support for giter8 in Scala Steward.

https://github.com/scala-steward-org/scala-steward/issues/1286#issuecomment-582083463

So I'm going to call updating sbt_version and scala_version out of scope for this issue.

**Comment by armanbilge** [comment]
I guess my question is, why do we need `sbt_version` in `default.properties` at all?

**Comment by valencik** [comment]
Oh.... hah....
Ok yeah, we weren't even using `sbt_version` anywhere :grimacing:  heh
Good catch

**Comment by valencik** [comment]
Resolved in https://github.com/typelevel/typelevel.g8/pull/14
