### ISSUE TITLE
Add typelevel.g8 to sbt-typelevel team

### ISSUE THREAD

**Issue by valencik** [typelevel/typelevel.g8#15]
I was chatting with @armanbilge, and perhaps we should add the `typelevel.g8` repo to the list of [repos in the `sbt-typelevel` team](https://github.com/orgs/typelevel/teams/sbt-typelevel/repositories) so everyone there has permissions here.

cc. @rossabaker I think we need your powers to do this.

**Comment by rossabaker** [comment]
Yeah, I think these two projects go hand-in-hand.  Generally, the more of this project that can be pushed into sbt-typelevel, the better, because then we all get maintenance after template instantiation.  I will merge the teams.

**Comment by rossabaker** [comment]
typelevel.g8 team is gone, sbt-typelevel team now includes @valencik, and everyone can maintain both sbt-typlevel and this.
